export const SWAGGER_API_TAG = {
  AUTH: 'AUTH',
  CUSTOMER: 'CUSTOMER',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  NOTES: 'NOTES',
  FAKE: 'FAKE',
  INVENTORY: 'INVENTORY',
  RESULTS: 'RESULTS',
  SPORTS: 'SPORTS',
  REGISTRATION: 'REGISTRATION',
  ADDFIXTURES: 'ADDFIXTURES',
  FIXTURES: 'FIXTURES',
  HIRING: 'HIRING',
};
